### ISSUE TITLE
Youka forum

### ISSUE THREAD

**Issue by unixfx** [Youka/NyuFX#4]
Hi Youka.
Actually I just want to inform you that I couldn't contact you unless here, Because there's something wrong with Forum, no one can post, write comment, and open any topic.

Thank you.

**Comment by Youka** [comment]
I'm already inactive for long time and my website host is lost, so it's rather possible the forum disappears than continues to work. You can contact me with PM in Aegisub or Doom9 forum or sometimes in IRC (@freenode @rizon).
